default: all

all: TwoWayDirectedGraph.java TwoWayDirectedGraphDriver.java
	javac TwoWayDirectedGraphDriver.java
	javac TwoWayDirectedGraph.java

run: TwoWayDirectedGraph.class TwoWayDirectedGraphDriver.class
	@java TwoWayDirectedGraphDriver